### ISSUE TITLE
Affichage des données du 8 et 9 mars (partiellement) manquantes

### ISSUE THREAD

**Issue by magopian** [etalab/covid19-dashboard#10]
Pour le 8 mars la seule bulle affichée est celle du grand-est. Pour le 9 mars il n'y a aucune bulle affichée.

**Comment by jdesboeufs** [comment]
C'est lié au fait que les données sont manquantes à ce stade.

**Comment by magopian** [comment]
Je suis en train de voir ça. D'ailleurs le graphique est un peu trompeur quand on regarde la popup :

<img width="360" alt="Capture d’écran 2020-03-16 à 12 44 17" src="https://user-images.githubusercontent.com/167767/76755322-f2cb2e00-6783-11ea-82cb-23793fd605de.png">

Il serait pertinent, à mon humble avis, d'avoir les jours "vides" affichés sur l'abscisse.

**Comment by magopian** [comment]
Je ferme ici maintenant qu'on affiche des colonnes vides pour les jours sans données
