### ISSUE TITLE
Problème légende 

### ISSUE THREAD

**Issue by Dams303** [etalab/covid19-dashboard#13]
La même couleur **orange** pour la légende (qui représente les cas en vie) est utilisée pour les cas confirmés alors que ce ne sont pas les mêmes chiffres à ce que j'ai compris:
cas confirmés = cas en vie + cas décédés.
Il faudrait changer cette couleur pour éviter la confusion et peut-être ajouter si ce sont des cas cumulés ou par jour.
<img width="399" alt="Capture d’écran 2020-03-16 à 13 41 45" src="https://user-images.githubusercontent.com/29258056/76759666-72f59180-678c-11ea-97f5-198682a0e3aa.png">

Bien cordialement.

**Comment by gillesboisson** [comment]
Je voulais proposer un fix pour cette issue mais je pense que les récentes modif de @jdesboeufs on corrigé cette incohérence

**Comment by Dams303** [comment]
Effectivement les changements effectués rendent cette issue invalide.
