### ISSUE TITLE
Text non lisible, contrast insuffisant 

### ISSUE THREAD

**Issue by rchod** [etalab/covid19-dashboard#134]
Le texte dans l'image attaché n'est pas lisible. 

L'orange sur fond blanc est limite, mais l'orange sur fond gris est illisible. 

![image](https://user-images.githubusercontent.com/623771/84688016-e26f4e80-af3e-11ea-868e-5e00e2f7b2d4.png)

**Comment by tmerlier** [comment]
Ce texte n'est plus présent.
