### ISSUE TITLE
Aide pour l'installation et Airtable API Key

### ISSUE THREAD

**Issue by Rivierg** [etalab/covid19-dashboard#147]
Bonjour, je trouve que le process d'installation n'est pas suffisamment documenté. J'ai cloné le repo et j'ai fait un `npm run dev ` comme indiqué, mais j'ai eu l'erreur:

```
error - ./components/layouts/prelevements/index.js:4:0 
Module not found: Can't resolve '../../../public/data/prelevements.json'
```

Je comprends donc qu'il faut récupérer les données JSON avec `npm run prepare-data`, mais c'est l'ordre inverse du README. Lorsque j'exécute cette commande j'obtiens:

```
Error: An API key is required to connect to Airtable
```

Est-ce qu'il faut que je crée un compte sur le site d'Airtable ? Et dans ce cas comment récupérer l'API key qui correspond à cette database ? Est-ce qu'elle est publique et permet l'accès en lecture ? Ce serait bien de documenter cela.

Merci d'avance

**Comment by leoceto** [comment]
Bonjour, même commentaire que Rivierg ici.... 

Merci de toute information sur le sujet AirTable car après la création d'un compte airtable et la génération d'une API positionnée dans le fichier .env, voici l'erreur obtenue par un yarn prepare-date 👍 
```
AirtableError {
  error: 'NOT_AUTHORIZED',
  message: 'You are not authorized to perform this operation',
  statusCode: 403
}
```

Comment peut on avancer sur le sujet ? D'avance merci

**Comment by drico** [comment]
Même commentaire, mais avec une proposition de solution :
Je pense que si quelqu'un ayant les droit d'accès pouvait créer un dossier `data.example` contenant le résultat à un instant donné d'une extraction des data, cela permettrai aux devs n'ayant pas d'accès à AirTable de pouvoir renommer ce dossier en `data` et de pouvoir développer.
D'avance merci !

**Comment by drico** [comment]
Après investigation, on peut accéder à une version du fichier `prelevements.json` à l'addresse suivante : https://dashboard.covid19.data.gouv.fr/data/prelevements.json

Cependant, il manque aussi (à minima) le fichier `dates.json` qui est lui aussi généré par `yarn prepare-data`, et celui-ci ne semble pas être accessible en ligne.

**Comment by jdesboeufs** [comment]
Ce n'est plus d'actualité.
Tout est désormais en lien avec des données ouvertes sur data.gouv.fr.

**Comment by jdesboeufs** [comment]
Je précise qu'il est désormais possible de lancer `yarn prepare-data` sans problème.
