### ISSUE TITLE
Seuils erronés sur le graphe des taux d'incidence

### ISSUE THREAD

**Issue by EnochMakenp** [etalab/covid19-dashboard#150]
Bonjour,
sur la carte des indicateurs les courbes présentent des lignes horizontale de couleur verte et rouge afin de figurer les seuils pour déterminer si pour cet indicateur nous sommes en vert (en dessous du seuil vert) en orange (entre les seuils vert et rouge) et en rouge (au dessus du seuil rouge).

Pour le taux d'incidence les seuils sont mal placées - le seuil vert devrait être à 10 (au lieu de 1 actuellment) et le seuil rouge à 50 (au lieu de 10 actuellement).

Merci !

**Comment by EnochMakenp** [comment]
L'erreur est dans le fichier /lib/indicators.js

tauxIncidence: {
    label: 'Taux d’incidence',
    details: 'Activité épidémique : nombre de patients ayant un test RT-PCR positif pour 100 000 habitants par semaine (cumul sur 7 jours glissants, données SI-DEP)',
    min: 10, <-- valeur à changer au lieu de 1
    max: 50 <-- valeur à changer au lieu de 10
  },

Cela prendra plus de temps de changer les valeurs "en direct" que de valider ma push request, d'où ma soumission peu orthodoxe, j'en conviens...

**Comment by EnochMakenp** [comment]
On a le même problème sur le taux de reproduction, la barre min (vert) est à 0 au lieu de 1...

**Comment by tmerlier** [comment]
Corrigé par #153
