### ISSUE TITLE
Maillage plus fin au niveau de la commune par exemple ?

### ISSUE THREAD

**Issue by voilier92000** [etalab/covid19-dashboard#160]
Les données au niveau départemental sont trop générales, surtout pour les départements très densément peuplés. 

Serait-il possible d'obtenir un maillage plus fin au niveau de la commune par exemple ?

**Comment by jdesboeufs** [comment]
Bonjour,

Vous trouverez par exemple ce jeu de données aux mailles communales, EPCI et IRIS : https://www.data.gouv.fr/fr/datasets/donnees-de-laboratoires-infra-departementales-durant-lepidemie-covid-19/
Il n'est pas prévu à ce stade de faire évoluer ce tableau de bord pour les intégrer.
