### ISSUE TITLE
Données de la carte des hospitalisations incohérentes

### ISSUE THREAD

**Issue by EricGarnier** [etalab/covid19-dashboard#164]
quand on demande des données du passé, à partir du 11 novembre, le carte des hospitalisations affiche des nombres et des tailles de rond bien trop important. Le total dépasse largement ce qui est affiché à gauche. Ceci se produit au moins sous edge et chrome.

![image](https://user-images.githubusercontent.com/22507413/99309685-1df9a600-285a-11eb-865f-5e65876189b3.png)

**Comment by jdesboeufs** [comment]
Merci pour votre retour.
Il y a en effet une anomalie dans les données régionales/départementales.
Nous allons investiguer cela.

**Comment by EricGarnier** [comment]
J'ai l'impression que parfois on affiche sur la carte le nombre de patients actuellement dans l'hôpital, et parfois le nombre total de patients qui sont passés par l'hôpital.
Les deux sont intéressants.

**Comment by jdesboeufs** [comment]
Il semble que ces colonnes soient inversées à certaines dates.
Nous avons remonté le problème à Santé publique France qui produit le fichier chaque jour.

**Comment by jdesboeufs** [comment]
C'est corrigé.
