### ISSUE TITLE
Données régionales manquantes des 8 et 9 mars ?

### ISSUE THREAD

**Issue by lou-dupont** [etalab/covid19-dashboard#22]
Sur https://veille-coronavirus.fr/, l'histogramme national est complet, mais les histogrammes par région sont troués pour les 8 et 9 mars. Les données n'ont pas été correctement importées ?

**Comment by magopian** [comment]
Si j'ai bien compris, elles n'ont pas été saisies à l'époque, et elles sont maintenant perdues (il n'y a plus moyen de les consulter, vu que la page de sante-publique-france est mise à jour tous les jours, on a plus accès à la version de ces jours-là).

À moins de trouver les données ailleurs, on a pas moyen de remplir ces trous :/

**Comment by Binnette** [comment]
Hello, ce n'est pas un bug de l'appli. Le problème c'est que certaines de nos sources de données (préfectures, Agence Régionale de Santé, etc) ne communiquent pas toujours leurs chiffres.

Je ferme cette issue. @lou-dupont je t'invite à jeter un œil aux données ici :
https://github.com/opencovid19-fr/data

Et à participer :wink:
