### ISSUE TITLE
Merci

### ISSUE THREAD

**Issue by valcriss** [etalab/covid19-dashboard#25]
Désolé d'utiliser le système des bugs, mais c’était juste pour vous dire merci pour votre travail sur ce projet.

**Comment by jdesboeufs** [comment]
🙏

**Comment by Binnette** [comment]
Salut @valcriss, n'hésites pas à partager la carte autour de toi ou sur tes réseaux sociaux. 👍 

En tout cas, merci pour ton message, cela fait très plaisir à toute l'équipe ❤️ 

PS : j'ai vu sur ton site que tu étais web designer et que tu faisais du dev, si tu as du temps libre, tu peux nous aider : https://github.com/opencovid19-fr/comment-contribuer
