### ISSUE TITLE
Les filtres autres que "cas confirmés" ne fonctionnent pas

### ISSUE THREAD

**Issue by liszto** [etalab/covid19-dashboard#37]

**Comment by liszto** [comment]
![image](https://user-images.githubusercontent.com/408031/77223059-7b1d4a80-6b59-11ea-81e4-a94b871323d0.png)

**Comment by liszto** [comment]
![image](https://user-images.githubusercontent.com/408031/77223072-9a1bdc80-6b59-11ea-874c-e1e186baa63d.png)

**Comment by liszto** [comment]
Précision : 
- Pour la dernière date, ils semblent ne pas fonctionner mais si on va sur la date précédente les données s'affichent.

**Comment by Binnette** [comment]
Glop. Je pense que ça fonctionne très bien. Mais par contre, on a plein de trous dans les data.

Mais bon entre ne pas avoir de données du tout et recopier les données de la veille, je préfère ne pas avoir les données. Car chaque donnée évolue tous les jours.

**Comment by Binnette** [comment]
@jdesboeufs, @tmerlier : il faudrait peut-être ajouter un message du style "Aucune donnée pour cette catégorie à cette date, changez de catégorie et/ou de date". Qu'en pensez-vous ?

**Comment by liszto** [comment]
La en l'occurence il y a des données. @Binnette 
J'avais ca ce matin pour les données du 20/03 sachant qu'on est le 21/03.
Ca me parait bizarre qu'on soit à aucun décès de renseigné dans les fichiers en date du 20/03 le 21/03 au matin ? 🤔 

Sachant qu'en se mettant sur les cas confirmés j'ai des données.

**Comment by fnx2k** [comment]
Je confirme même comportement aujourd'hui:
seuls les cas confirmés sont affichés alors que les données existent dans les histogrammes de gauche. (fig.1 et 2)

![Screenshot_20200322_122813](https://user-images.githubusercontent.com/24877447/77248529-56e56a80-6c3a-11ea-9342-ecdedfa9a4d5.png)
![Screenshot_20200322_123007](https://user-images.githubusercontent.com/24877447/77248533-5cdb4b80-6c3a-11ea-8165-a2ca5f1d03d4.png)

Après essai,  l'affichage se fait sur les dates antérieures au 21/03. (fig 3.)
Ca ressemble à un bug de pointeur.
![Screenshot_20200322_124226](https://user-images.githubusercontent.com/24877447/77248570-c3f90000-6c3a-11ea-9d1b-febddc7cb7c0.png)


Mais un message du type "pas de données pour ce jour" serait le bienvenu pour penser à changer la date d'affichage

**Comment by Florimondable** [comment]
Oui, s'il vous plait mettez quelque chose lorsqu'il n'y a pas de donnée, j'ai mis du temps à comprendre que ce n'était pas un bug :/

**Comment by tmerlier** [comment]
L'absence de données est indiquée depuis quelque temps par le message suivant:
![Capture d’écran 2020-10-09 à 16 15 30](https://user-images.githubusercontent.com/7040549/95594189-e9b8eb80-0a4a-11eb-90d6-7d71d2c534f3.png).

Je ferme cette issue avec un peu de retard désolé…
