### ISSUE TITLE
Les filtres par département ne fonctionnent pas également.

### ISSUE THREAD

**Issue by liszto** [etalab/covid19-dashboard#38]

**Comment by liszto** [comment]
![image](https://user-images.githubusercontent.com/408031/77223066-8b352a00-6b59-11ea-816e-e6edc427bf0d.png)

**Comment by liszto** [comment]
Le souci pour les départements semblent être le même que pour les régions. Si on prend une journée autre que la dernière date disponible les résultats semblent bien s'afficher.

**Comment by Binnette** [comment]
Hello @liszto, le bug n'est pas présent en 'dev' sur la branche master.
![image](https://user-images.githubusercontent.com/6597721/77231745-24d1fb00-6b9d-11ea-8d52-0b8e96bb4513.png)

Je vais voir avec @jdesboeufs si je peux republier le site.

Remarque @tmerlier, peut peut-être me donner le feu vert pour redéployer le dashboard sur gh-pages ? :wink:

**Comment by liszto** [comment]
Cool ! :)
Je clos alors. Si jamais ça apparaît après déploiement je pourrais toujours rouvrir l'issue

**Comment by jdesboeufs** [comment]
En fait les dernières données sont embarquées lors du déploiement.
Donc lorsqu'il y a que des trous, c'est vide :(

**Comment by liszto** [comment]
Ah oui j'oublie à chaque fois cette notion de trou. J'arrête pas de croire que ca reprend les données du dernier jour valide. Mais non :) je vais m'y faire
