### ISSUE TITLE
Firefox,  WebGL creation failed: * tryNativeGL * Exhausted GL driver options.

### ISSUE THREAD

**Issue by rchod** [etalab/covid19-dashboard#44]
Bonjour,

![Screenshot from 2020-03-21 18-29-45](https://user-images.githubusercontent.com/623771/77232584-2fdb5a00-6ba2-11ea-997f-9827794a4604.png)

J'ai un écran blanc au lieu de la map sur mon nouveau PC

Après un peu de [recherche](https://bugzilla.mozilla.org/show_bug.cgi?id=1416016)  j'ai mis `security.sandbox.content.level` à `2` et la j'arrive à voir la map

**Comment by jdesboeufs** [comment]
Bonjour,

En effet WebGL doit être actif sur votre navigateur.
C'est très généralement la cas.

**Comment by rchod** [comment]
juste pour précision WebGL était bien actif sur Firefox, c'est un bug Firefox et pour le corriger il faut soit whitelister les fichiers
```
/sys/class/drm/card0/device/config
/sys/class/drm/renderD128/device/config
/sys/class/drm/controlD64/device/config
```
ou 
`/sys/devices/pci0000:00/0000:00:02.0/subsystem`

soit baisser le niveau de sandbox à 2, je partage juste si quelqu'un d'autre tombe sur le même soucis

**Comment by jdesboeufs** [comment]
Vous savez quelles versions sont concernées ?

**Comment by rchod** [comment]
je pense c'est plus lié à la version de la carte graphique (**intel hd graphics 520**) que à la version de Firefox, voilà un lien vers le bug https://bugzilla.mozilla.org/show_bug.cgi?id=1417291
Et je suis sur la dernière version de Firefox 74.0

**Comment by woctezuma** [comment]
Merci pour ce fil de discussion : la carte ne s'affichait pas sur mon PC portable, et je me suis rendu compte que [WebGL avait été désactivé](https://superuser.com/questions/836832/how-can-i-enable-webgl-in-my-browser) dans `about:config` de Firefox (option `webgl.disabled` dont la valeur par défaut avait été modifiée). J'aurais presque pu abandonné si je n'avais pas trouvé les messages postés ici.
