### ISSUE TITLE
"An unexpected error has occurred."

### ISSUE THREAD

**Issue by Eymiks** [etalab/covid19-dashboard#45]
Bonjour vu que je savais pas comment décrire la marche à suivre je vous partage une vidéo : https://drive.google.com/file/d/1AQ7tAJkQrjEzGsNcZ9zcolYbByvR7YOF/view

**Comment by dimitri-bourreau** [comment]
Bonjour,

**Problème rencontré**
- A la sélection de la carte des cas confirmés, aucune donnée n'est affichée (jour du 21 mars, à date d'aujourd'hui).
- En allant à j-1 des données sont affichées.
- En cliquant sur une ville, puis en allant à j+1 (retour au jour actuel) : **An unexpected error has occurred**. apparaît.

Ce défaut ne semble survenir que sur les cartes départementales.

**Anomalie**
L'anomalie vient de ce bout de code : à la ligne 125, feature retourne _undefined_ lorsqu'on clique pour aller à j+1 (jour actuel).

https://github.com/opencovid19-fr/dashboard/blob/1db70c1f9219ec09cd52b8a46ea4a4d9b22a29d6/pages/index.js#L116-L127

Je suis dessus, mais j'ai un niveau très débutant alors si quelqu'un est habitué à ce code et a le temps qu'il ne se prive pas. Je reviens dès que j'ai une PR à présenter. :)
