### ISSUE TITLE
Comparaison avec les autres pays 

### ISSUE THREAD

**Issue by JiPiBi** [etalab/covid19-dashboard#52]
Bonjour la plupart des dashboards que j'ai parcourus ces derniers jours utilisent les comparaisons entre pays 
quelques exemples pour alimenter votre reflexion 

https://public.tableau.com/profile/jean.paul.cavalier#!/vizhome/Coronavirus2019-nCoVstats/Coronavirus2019-nCoV

https://flattenthecurve.co.nz/

https://avatorl.org/covid-19/

https://datastudio.google.com/u/0/reporting/9ce371f1-62fa-4f2e-8d3c-da4d6dff967b

**Comment by dhrou** [comment]
les dev font comme ils veulent mais perso il vaut mieux traiter le mieux possible la situation franco-française qu'essayer de faire un énième dashboard mondial

**Comment by JiPiBi** [comment]
@dhrou  oui c est vrai on n'a pas grand chose à  apprendre des autres :-(
