### ISSUE TITLE
Question naive sur le fonctionnement du dashboard

### ISSUE THREAD

**Issue by JiPiBi** [etalab/covid19-dashboard#55]
Je n'ai pas compris le principe de ce dashboard : 
- j'ai vu dans le read me qu'il nécessitait node.js , je l'avais déjà installé en version 12.13.0 , je pense dans le cadre d'une formation js
- je comprends un peu le langage , mais je ne comprends pas le principe de ce  dashboard 

Ma principale question est donc  peut on utiliser votre dashboard sans etre un expert js 
- si oui que faut il faire ?
- si non , je me contenterai de consulter d'autres sites clés en main ....

**Comment by jdesboeufs** [comment]
Bonjour.
Cet outil est en ligne : https://veille-coronavirus.fr

**Comment by JiPiBi** [comment]
Merci beaucoup  👍
