### ISSUE TITLE
Afficher la derniere info dispo dans la carte

### ISSUE THREAD

**Issue by mckmonster** [etalab/covid19-dashboard#57]
Actuellement la carte n'affiche que la donnée du jour ce qui fait que l'on a pas d'info des fois.
Alors que l'on a l'info pour le jour d'avant.

Je ne sais pas ce que vous en pensez, mais je préfère ne pas avoir d'info à jour que rien du tout.
Après, il peut y avoir un code pour dire que ce n'est pas l'info du jour.

**Comment by jdesboeufs** [comment]
Merci @mckmonster.
C'est en effet ce qu'on va faire dans les plus brefs délais !
