### ISSUE TITLE
Problème d'affichage sur la dernière date quand on choisit une région

### ISSUE THREAD

**Issue by ThomasG77** [etalab/covid19-dashboard#59]
Voir le GIF pour illustrer
![issue-last-date](https://user-images.githubusercontent.com/642120/77569064-e6547d00-6ec9-11ea-9be9-4e072c89c81a.gif)

**Comment by jdesboeufs** [comment]
Ah oui on a plus d'hospitalisations + décès + guéris que de cas confirmés…

**Comment by jdesboeufs** [comment]
Merci pour le signalement @ThomasG77

**Comment by jdesboeufs** [comment]
Un problème dans les données on investigue.

**Comment by jdesboeufs** [comment]
C'est corrigé. Des doublons dans le fichier Santé publique France, et un `Array.reduce()` malheureux qui sommait donc en double.

**Comment by ThomasG77** [comment]
Merci
