### ISSUE TITLE
Positionnement sur la carte de la Haute corse

### ISSUE THREAD

**Issue by rosorio** [etalab/covid19-dashboard#6]
Bonjour,

Je n'ai pas creusé plus avant mais sur le tableau de bord (https://veille-coronavirus.fr/)
les chiffres de Haute Corse sont placé au nord de l'aquitaine et la Corse du Sur sur la
la Corse du nord.

Cordialement,
-- rodrigo

**Comment by Binnette** [comment]
@rosorio tu m'as pris de court 😉 Je confirme le bug.
![image](https://user-images.githubusercontent.com/6597721/76690269-c2c64280-663e-11ea-9bec-2ec3f78b09e5.png)

**Comment by jdesboeufs** [comment]
Les données par département (incomplètes) ont été déployées par erreur pendant quelques minutes.
Mais on va regarder car ce n'est pas normal. 🤔

**Comment by rosorio** [comment]
Le problème semble corrigé

**Comment by jdesboeufs** [comment]
Il ne l'est pas encore, on est juste repassé en régional.
Par contre le bug a été identifié, il s'agissait d'une erreur de saisie des codes département :
https://github.com/opencovid19-fr/data/pull/33

**Comment by rosorio** [comment]
Oh désolé je vous laisse la fermer alors

**Comment by jdesboeufs** [comment]
En tout cas merci pour le signalement 🙏
