### ISSUE TITLE
Le nombre de "cas confirmé" par département n'est plus visible

### ISSUE THREAD

**Issue by mckmonster** [etalab/covid19-dashboard#64]
![image](https://user-images.githubusercontent.com/6614890/77734807-ac8a9000-7009-11ea-9e46-ca40ffc747e4.png)

**Comment by NeptisPID** [comment]
Cela provient probablement du fait que les données ont changé au niveau format. Exemple avec le departement DEP-68: 

{
    "date": "2020-03-06",
    "source": {
      "nom": "Coronavirus-France-Dataset",
      "url": "https://github.com/lperez31/coronavirus-france-dataset"
    },
    "sourceType": "lperez31-historical-data",
    "casConfirmes": 80,
    "code": "DEP-68",
    "nom": "Haut-Rhin"
  },

Depuis le 17 Mars on a : 

{
    "code": "DEP-68",
    "nom": "Haut-Rhin",
    "date": "2020-03-25",
    "hospitalises": 802,
    "reanimation": 106,
    "deces": 239,
    "gueris": 325,
    "source": {
      "nom": "Santé publique France Data"
    },
    "sourceType": "sante-publique-france-data"
  },

A noter, que c'est toujours disponible dans certains départements.

**Comment by 303055** [comment]
Bonjour

Pourquoi il été fermé sans correctif ?

@+

**Comment by mckmonster** [comment]
@303055 
De ce que je viens de voir une autre MR a été validé.
Qui supprime complètement cette info

**Comment by rchod** [comment]
@mckmonster  ce bug peut être fermé non ?

**Comment by mckmonster** [comment]
Yep

**Comment by 303055** [comment]
Oui on peut le fermer .... mais il n'est pas réparé..... il n'y a plus de remonté des cas .... ça sent la mort du petit cheval pour ce site... il est gouvernemental ?
