### ISSUE TITLE
Améliorer l'affichage des courbes régionales sur mobile

### ISSUE THREAD

**Issue by pachevalier** [etalab/covid19-dashboard#7]
Actuellement la courbe de détail des évolutions par régions est assez peu lisible sur téléphone. Possible de centrer la box ?

**Comment by jdesboeufs** [comment]
On a bien identifié ce problème, mais pour le moment on a pas trouvé de solution simple.
Normalement la bibliothèque Mapbox GL JS gère ça toute seule, quelque chose a dû nous échapper.
