### ISSUE TITLE
Ajouter un lien permanent par département ou région

### ISSUE THREAD

**Issue by Toub** [etalab/covid19-dashboard#72]
Il est très utile de communiquer via les réseaux sociaux en postant un lien vers https://dashboard.covid19.data.gouv.fr/ ou https://www.gouvernement.fr/info-coronavirus/carte-et-donnees

Cependant, la carte est toujours centrée sur la France métropolitaine, même si c'est l'ARS du Grand Est ou de La Réunion qui communique par exemple.
 
Pourquoi ne pas ajouter un paramètre dans l'URL permettant de:
- filtrer les données par région ou département (exactement comme lorsque l'on clique sur un département)
- centrer la carte sur la région concernée
- zoomer sur la région concernée

Exemple de lien: https://dashboard.covid19.data.gouv.fr/?dep=44

On pourra par la suite ajouter d'autres paramètres, par exemple pointer sur une date du passé.

__Je peux proposer une PR__, mais j'aimerais avoir l'accord avant de passer du temps sur le sujet.

Proposition initialement postée ici en commentaire: https://github.com/etalab/covid19-dashboard/issues/42#issuecomment-605609439

**Comment by Toub** [comment]
@jdesboeufs un avis? Je passe peut-être à côté de quelque chose?

**Comment by jdesboeufs** [comment]
C'est chose faite : https://dashboard.covid19.data.gouv.fr/regions/44
https://dashboard.covid19.data.gouv.fr/departements/75

**Comment by Toub** [comment]
Super, du bon travail!

Et aussi l'affichage des DOM, très propre!
