### ISSUE TITLE
Rajouter le delta J-1 en affichage maille départementale

### ISSUE THREAD

**Issue by bdahon** [etalab/covid19-dashboard#83]
Lorsque l'on choisit l’évolution à la maille départementale, le delta par rapport à la veille ne s'affiche pas
![image](https://user-images.githubusercontent.com/5084243/78820273-cb106400-79d7-11ea-8f52-5efa1465e47d.png)

**Comment by tmerlier** [comment]
Les deltas sont désormais disponible à la maille départementale.
